[build]
  command = "rm -rf flutter && git clone https://github.com/flutter/flutter.git -b 3.27.0 && export PATH=\"$PATH:$(pwd)/flutter/bin\" && flutter pub get && flutter build web --release --no-tree-shake-icons"
  publish = "build/web"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
